# Generated by Django 2.1.5 on 2019-09-05 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 9, 5, 16, 36, 48, 967003), verbose_name='creation date')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
