# Generated by Django 2.1.5 on 2019-09-07 19:15

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 22, 15, 24, 183482), verbose_name='creation date'),
        ),
    ]
