# Generated by Django 2.1.5 on 2019-09-07 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_app', '0002_auto_20190907_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 22, 45, 48, 66282), verbose_name='creation date'),
        ),
    ]
