# Generated by Django 2.1.5 on 2019-09-08 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_app', '0003_auto_20190907_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 20, 5, 19, 99323), verbose_name='creation date'),
        ),
    ]
